name: CI Pipeline

on:
  push:
    branches:
      - main  # Exécute le workflow sur les pushs vers la branche "main"
  pull_request:
    branches:
      - main  # Exécute le workflow sur les pull requests vers "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # Étape 4 : Lancer les tests unitaires
    - name: Run tests
      run: |
        source .venv/bin/activate
        python -m unittest discover -s . -p "*.py"
